package br.com.davidbuzatto.cprl.ide.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 * CPRL IDE main window.
 * 
 * @author Prof. Dr. David Buzatto
 */
public class MainWindow extends javax.swing.JFrame {
    
    private RSyntaxTextArea sourceCodeArea;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setupSourceCodeArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnSaveAll = new javax.swing.JButton();
        sep01 = new javax.swing.JToolBar.Separator();
        btnCompile = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        tabbedPaneSourceCode = new javax.swing.JTabbedPane();
        scrollPaneConsole = new javax.swing.JScrollPane();
        textPaneConsole = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuEdit = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CPRL IDE");

        toolbar.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/page_white_add.png"))); // NOI18N
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnNew);

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder.png"))); // NOI18N
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnOpen);

        btnSaveAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disk_multiple.png"))); // NOI18N
        btnSaveAll.setFocusable(false);
        btnSaveAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnSaveAll);
        toolbar.add(sep01);

        btnCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrench.png"))); // NOI18N
        btnCompile.setFocusable(false);
        btnCompile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnCompile);

        btnRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow_right.png"))); // NOI18N
        btnRun.setFocusable(false);
        btnRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnRun);

        splitPane.setDividerLocation(300);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setLeftComponent(tabbedPaneSourceCode);

        scrollPaneConsole.setViewportView(textPaneConsole);

        splitPane.setBottomComponent(scrollPaneConsole);

        menuFile.setText("File");
        menuBar.add(menuFile);

        menuEdit.setText("Edit");
        menuBar.add(menuEdit);

        menuHelp.setText("Help");
        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void main( String args[] ) {
        FlatDarkLaf.setup();
        java.awt.EventQueue.invokeLater( () -> new MainWindow().setVisible( true ) );
    }
    
    private void setupSourceCodeArea() {
        
        sourceCodeArea = new RSyntaxTextArea(20, 60);
        sourceCodeArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        sourceCodeArea.setCodeFoldingEnabled(true);
        
        RTextScrollPane sp = new RTextScrollPane(sourceCodeArea);
        tabbedPaneSourceCode.addTab( "teste", sourceCodeArea );
        
        try {
            loadSourceCode( "test.cprl" );
        } catch ( Exception exc ) {
            exc.printStackTrace();
        }
        
    }
    
    private void loadSourceCode( String path ) throws IOException {
        
        Scanner s = new Scanner( new File( path ) );
        StringBuilder sb = new StringBuilder();
        
        while ( s.hasNextLine() ) {
            sb.append( s.nextLine() ).append( "\n" );
        }
        
        sourceCodeArea.setText( sb.toString() );
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompile;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnSaveAll;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JScrollPane scrollPaneConsole;
    private javax.swing.JToolBar.Separator sep01;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTabbedPane tabbedPaneSourceCode;
    private javax.swing.JTextPane textPaneConsole;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
